auditbeat.modules:

- module: auditd
  audit_rules: |
    -w /var/log/apache2 -p wa -k identity
    #-a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: file_integrity
  paths:
    - /bin
    # - /usr/bin
    # - /sbin
    # - /usr/sbin
    - /etc

- module: system
  datasets:
    - host
    - login
    - package
    - user
  period: 1m

  user.detect_password_changes: true

- module: system
  datasets:
    - process
    - socket
  period: 1s
  
processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]