auditbeat.modules:

#  - module: auditd
#    audit_rules: |
# #     -w /etc/passwd -p wa -k identity
#       -a always,exit -F arch=b32 -S open,creat,truncate,ftruncate,openat,open_by_handle_at -F exit=-EPERM -k access

- module: file_integrity
  paths:
    - /bin
    - /usr/bin
    - /sbin
    - /usr/sbin
    - /etc
  scan_at_start: true

- module: system
  datasets:
    - host
    - login
    - package
    - user
  period: 1m

  user.detect_password_changes: true

- module: system
  datasets:
    - process
    #- socket
  period: 1s
  
processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]